-- =================================================================
-- MESSAGES & INBOX SETUP
-- =================================================================
-- Instructions:
-- This script creates the 'messages' table and sets up the
-- necessary security policies for the inbox feature to work correctly.
--
-- Please run this script once in your Supabase SQL Editor.
-- =================================================================

-- 1. Create the messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    content text,
    read boolean DEFAULT false NOT NULL
);

-- 2. Enable Row Level Security for the messages table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for the messages table
DROP POLICY IF EXISTS "Users can view their own messages." ON public.messages;
CREATE POLICY "Users can view their own messages."
    ON public.messages FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own messages." ON public.messages;
CREATE POLICY "Users can insert their own messages."
    ON public.messages FOR INSERT
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own messages." ON public.messages;
CREATE POLICY "Users can update their own messages."
    ON public.messages FOR UPDATE
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own messages." ON public.messages;
CREATE POLICY "Users can delete their own messages."
    ON public.messages FOR DELETE
    USING (auth.uid() = user_id);

-- 4. Grant usage for the new table
GRANT ALL ON public.messages TO authenticated;
GRANT ALL ON public.messages TO service_role;

-- Example of how to insert a message for a user (for testing):
-- INSERT INTO public.messages (user_id, title, content)
-- VALUES ('YOUR_USER_ID_HERE', 'Welcome to Rentify!', 'This is your first message in your new inbox.'); 