import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Check } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../components/ui/Button';
const PricingPage = () => {
    return (_jsx("div", { className: "max-w-6xl mx-auto py-12 px-4", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: [_jsxs("div", { className: "text-center mb-16", children: [_jsx("h1", { className: "text-4xl font-bold mb-4", children: "Simple, Transparent Pricing" }), _jsx("p", { className: "text-lg text-muted-foreground max-w-2xl mx-auto", children: "Focus on sharing, not on fees. We handle the hard parts so you can rent and earn with confidence." })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 items-center", children: [_jsxs("div", { className: "bg-card border rounded-lg p-8 space-y-6", children: [_jsx("h2", { className: "text-2xl font-bold", children: "For Renters" }), _jsx("p", { className: "text-muted-foreground", children: "Pay for what you rent, that's it. We add a small service fee to help us run the platform and provide support." }), _jsxs("ul", { className: "space-y-4", children: [_jsxs("li", { className: "flex items-center gap-3", children: [_jsx(Check, { className: "text-green-500 w-5 h-5" }), " Secure Payments"] }), _jsxs("li", { className: "flex items-center gap-3", children: [_jsx(Check, { className: "text-green-500 w-5 h-5" }), " Damage Protection Options"] }), _jsxs("li", { className: "flex items-center gap-3", children: [_jsx(Check, { className: "text-green-500 w-5 h-5" }), " 24/7 Community Support"] })] }), _jsx("p", { className: "text-sm text-muted-foreground pt-4 border-t", children: "A small, variable service fee is added at checkout." })] }), _jsxs("div", { className: "bg-card border rounded-lg p-8 space-y-6", children: [_jsx("h2", { className: "text-2xl font-bold", children: "For Owners" }), _jsx("p", { className: "text-muted-foreground", children: "Listing is free. We only take a small commission from your earnings after a successful rental." }), _jsxs("ul", { className: "space-y-4", children: [_jsxs("li", { className: "flex items-center gap-3", children: [_jsx(Check, { className: "text-green-500 w-5 h-5" }), " Free Unlimited Listings"] }), _jsxs("li", { className: "flex items-center gap-3", children: [_jsx(Check, { className: "text-green-500 w-5 h-5" }), " Owner Protection Guarantee"] }), _jsxs("li", { className: "flex items-center gap-3", children: [_jsx(Check, { className: "text-green-500 w-5 h-5" }), " Fast & Secure Payouts"] })] }), _jsx("p", { className: "text-sm text-muted-foreground pt-4 border-t", children: "A 15% commission is deducted from your rental earnings." })] })] }), _jsxs("div", { className: "text-center mt-16", children: [_jsx("h3", { className: "text-2xl font-bold", children: "Ready to Get Started?" }), _jsx("p", { className: "text-muted-foreground mt-2 mb-6", children: "Join thousands of users saving money and reducing waste." }), _jsx(Link, { to: "/auth", children: _jsx(Button, { size: "lg", children: "Sign Up for Free" }) })] })] }) }));
};
export default PricingPage;
